11-14 Quant Gen
========================================================

Working further with
$$
\Delta \bar{Z} = G \beta
$$

$G$ is the genetic variance covariance matrix
$\beta$ vector measures the direct selection

Lande and Arnold - Multiple regression
 - multiple predictors of fitness
 - $\beta$ s are the partial regression coefficient

Regression equation:
$$
w = \beta_1 Z_1 + \beta_2 Z_2 + \ldots + error
$$

But then there's another way to look at the change in traits
$$
\Delta \bar{Z} = Cov_A(w,Z)
$$


### G X E interaction

genotpye by environment interaction is the nonparallelism in the reaction to different envrionments

The different environments are "macroenvironments" - large enough to contain the different genotypes. environments could be 

#### Example

fullsib nested withing halfsib crosses, grown in 2 or more different macroenvironments.
ANOVA would analyze the variances
 - random: sires, dames, within
 - fixed: environment
 - interactions: sire X environment, dam X environment  
From the interactions we could components of variance, $\sigma^2_{s\times E}$, and this could be thought of as the breeding values responding to environmental effects. 


Group discussion
------------------
- environment change could be more gradual than the differences in environment
 - strong selection depletes genetic variation to be selected on
 - weak selection wouldn't deplete that as much
- OK dry - would make the environemental differences more extreme
- gene migration could be a method of adaptation to changing environments
 - but pop fragmentation prevents this
