11-19 Quant Gen
========================================================


$\sigma^2_{SXe}\rightarrow$ G X E interaction die to the change in breeding values

we have a GxE interaction any time we have a nonparallelism in the reaction norms
 - change in rank of different Genotypes fitness in different environments
 - or same rank, just wider differences between the groups
 
one can also use $r_g$, the correlation of trait in E1, with trait in E2. Trait measured in two different environments. This is the genetic correlation between traits in different environments

$$
\sigma^2_{gxe} = \frac{\left[(\sigma_{g1} - \sigma_{g2})^2 + \sigma_{g1}\sigma_{g2}(1 - r_{g12})   \right]}{2}
$$

This is way of partitioning the variances, $(\sigma_{g1} - \sigma_{g2})^2$ is ... 


one should not confuse GxE with G-E correlaiton
- GxE interaction
- G-E correlation: a nonrandom association between genotypes and the nature of environments in which they occurr.



-------------------------------
## Inbreeding

inbreeding changes genotpye frequencies, not allele frequencies. It increased the frequencies of homozygotes

Geneotype frequencies with inbreeding  

Geneotype | HW | Inbreeding  
--------------|------------|---------------  
A1A1 | $p^2$ | $p^2(1-F) +pF$  
A1A2 | $2pq$ | $2pq - 2Fpq$  
A2A2 | $q^2$ | $q^2(1-F) + qF$  

Definition of effecctive inbreeding is the mean of an inbred pop - mean of random mating pop


